- hosts: all
  become: yes
  tasks:
   - name: install salt repo
     command: yum install https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el8.noarch.rpm -y

   - name: install salt master and minion
     command: yum install salt-master salt-minion -y 
