- hosts: all
  become: yes
  tasks:
   - name: install docker repo
     command: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

   - name: install Docker and vim
     command: dnf install vim docker-ce --nobest -y

   - name: install containerd
     command: dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.10-3.2.el7.x86_64.rpm -y

   - name: start Docker
     service:
       name: docker
       enabled: yes
       state: started

   - name: disable SELinux
     command: setenforce 0
     register: result
     failed_when: result.rc > 1

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: switch off swap
     command: swapoff -a

   - name: Disable swap in fstab
     replace:
       path: /etc/fstab
       regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
       replace: '# \1'

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.19.0
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.19.0
        state: present

   - name: configure kubelet extra params
     copy:
       dest: "/etc/sysconfig/kubelet"
       content: |
         KUBELET_EXTRA_ARGS=  --runtime-cgroups=/systemd/system.slice --kubelet-cgroups=/systemd/system.slice

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.19.0
        state: present
        allow_downgrade: yes
